### ISSUE TITLE
diff command failed: command `git` failed: exit status 128

### ISSUE THREAD

**Issue by dep** [monebag/monorepo-diff-buildkite-plugin#115]
I ran into this error during my configuration:

```
- label: ":white_check_mark: Test Coverage"
  timeout_in_minutes: 10
  agents:
    queue: ruby-2-7
    ruby: 2.7
  plugins:
  - monebag/monorepo-diff#v2.5.0:
      diff: git diff --name-only HEAD $(git merge-base HEAD origin/master)
      watch:
        - path:
            - "test/"
            - "client/"
            - "app/"
            - "components/"
            - "components/"
            - "bin/"
          config:
            command: ruby bin/ci_pipeline/test_coverage.rb
```

Error:

```
INFO[0000] --- :one: monorepo-diff v2.5.0
INFO[2022-11-15T17:49:52Z] Running diff command: git diff --name-only HEAD $(git merge-base HEAD origin/master)
FATA[2022-11-15T17:49:52Z] diff command failed: command `git` failed: exit status 128
🚨 Error: The command exited with status 1
```

Thanks for any help!

**Comment by adikari** [comment]
It feels like it's not the issue with the plugin but the git command you are using. With the information you have provided it's hard to know what the error might be.

You can try running the git command outside of the plugin in a separate step and see if it still throws an error?

**Comment by dep** [comment]
Thanks for the lead. Had to go after this in a slightly different way:

```
- monebag/monorepo-diff#v2.5.0:
    diff: git remote set-branches --add origin production > /dev/null && git checkout $BUILDKITE_COMMIT > /dev/null && git diff --name-only origin/production
    watch:
      - path:
          - "**/*.json"
          - "**/*.js"
        config:
          command: ruby bin/ci_pipeline/test_coverage.rb
```
