### ISSUE TITLE
could not initialize plugin

### ISSUE THREAD

**Issue by GZLiew** [monebag/monorepo-diff-buildkite-plugin#116]
Hi the plugin suddenly stopped working for us

$ /var/lib/buildkite-agent/plugins/github-com-chronotc-monorepo-diff-buildkite-plugin/hooks/command
--
  | https://github.com/monebag/monorepo-diff-buildkite-plugin/releases/latest/download/monorepo-diff-buildkite-plugin-linux-arm64
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  | 100 3244k  100 3244k    0     0  3903k      0 --:--:-- --:--:-- --:--:-- 3903k
  | INFO[0000] --- :one: monorepo-diff v2.5.0
  | FATA[0000] could not initialize plugin

**Comment by adikari** [comment]
please provide more information about the issue. your configuration file will help.

**Comment by mogggggg** [comment]
I'm seeing the same error except we're using the amd64 binary. Here's a snippet of our configuration:

```yaml
steps:
  - label: ":octocat: Checking for artifact changes on the develop branch..."
    agents:
      queue: infra-develop-x86-64
    branches: "!master"
    plugins:
      - chronotc/monorepo-diff#v2.5.0:
          diff: .buildkite/ci/git-diff.sh
          log_level: debug
          watch:
            - path:
                - artifacts/docker/
                - .buildkite/artifacts-docker.yml
                - .buildkite/ci/artifacts-docker.sh
              config:
                trigger: my-docker-pipeline-name
                async: true
                build:
                  env:
                    - PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
            - path:
                - artifacts/packer/
                - .buildkite/artifacts-packer.yml
                - .buildkite/ci/artifacts-packer.sh
              config:
                trigger: my-packer-pipeline-name
                async: true
                build:
                  env:
                    - PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
```
