### ISSUE TITLE
[Help] Runner shows the outgoing steps but doesn't actually run them?

### ISSUE THREAD

**Issue by dep** [monebag/monorepo-diff-buildkite-plugin#117]
I have a wokflow that looks like this:

```
- label: ":coffee: Legacy Client Tests"
  timeout_in_minutes: 60
  env:
    NODE_VERSION: 12.22.7
    GRUNT_QUIET: 'true'
  agents:
    queue: client-tests-ruby-2-7
    ruby: 2.7
  plugins:
  - improbable-eng/metahook#v0.4.1:
      pre-command: ./bin/ci_pipeline/client_test_setup.sh
  - monebag/monorepo-diff#v2.5.0:
      diff: "git diff --name-only HEAD~1"
      watch:
        - path:
          - "yarn.lock"
          - "app/"
          - "backdraft/"
          - "client/"
          - "components/"
          - "test/"
          config:
            command: grunt coffee-test
            agents:
              queue: client-tests-ruby-2-7
              ruby: 2.7
```

Unfortunately when it runs, it prints this:

```
$ /buildkite/plugins/github-com-monebag-monorepo-diff-buildkite-plugin-v2-5-0/hooks/command
--
  | https://github.com/monebag/monorepo-diff-buildkite-plugin/releases/download/v2.5.0/monorepo-diff-buildkite-plugin-linux-amd64
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  | 100 3293k  100 3293k    0     0  27.1M      0 --:--:-- --:--:-- --:--:--  139M
  | INFO[0000] --- :one: monorepo-diff v2.5.0
  | INFO[2022-11-18T11:44:48-08:00] Running diff command: git diff --name-only HEAD~1
  | Generated Pipeline:
  | steps:
  | - command: grunt coffee-test
  | agents:
  | queue: client-tests-ruby-2-7
  | ruby: ""
```

I see the `command` I want to run there, `grunt coffee-test` but the command never runs.

```
  | Generated Pipeline:
  | steps:
  | - command: grunt coffee-test
  | agents:
  | queue: client-tests-ruby-2-7
  | ruby: ""
  |  
  | Running global post-command hook | 0s
  | ⚠️ Warning: Value of DATABASE_MYSQL_PASSWORD below minimum length and will not be redacted
  | ⚠️ Warning: Value of BUNDLE_SILENCE_ROOT_WARNING below minimum length and will not be redacted
  | $ /buildkite/hooks/post-command
  | Running plugin metahook post-command hook
```
