### ISSUE TITLE
FATA[2022-12-06T22:43:41Z] diff command failed: command `git` failed: exit status 128

### ISSUE THREAD

**Issue by dep** [monebag/monorepo-diff-buildkite-plugin#119]
Using the example in your README throws an error:

```
steps:
  - label: "Unit Test Pipeline"
    plugins:
      - monebag/monorepo-diff#v2.5.0:
          diff: "git diff --name-only $(head -n 1 last_successful_build)"
          hooks:
            - command: "echo $(git rev-parse HEAD) > last_successful_build"
          watch:
            - path:
                - "applications/react/modern/feature-administration/**"
              config:
                - label: "Feature Administration"
                  <<: *default_config
                  commands:
                    - "make titan-feature-administration"
                    - "make test-titan-feature-administration"
            - path:
                - "applications/react/legacy/temporary-access/**"
              config:
                - label: "Temporary Access"
                  <<: *default_config
                  commands:
                    - "make titan-temporary-access"
                    - "make test-titan-temporary-access"
            - path: 
                - "applications/react/modern/template/**"
              config:
                - label: "Template"
                  <<: *default_config
                  commands:
                    - "make titan-template"
                    - "make test-titan-template"
            - path:
                - "applications/react/modern/login-hero/**"
              config:
                - label: "Login Hero"
                  <<: *default_config
                  commands:
                    - "make titan-login-hero"
                    - "make test-titan-login-hero"
            - path:
                -"applications/react/legacy/legacy-template/**"
              config:
                - label: "Legacy Template"
                  <<: *default_config
                  commands:
                    - "make titan-legacy-template"
                    - "make test-titan-legacy-template"
            - path:
                - "applications/react/legacy/invoca-tags/**"
              config:
                - label: "Invoca Tags"
                  <<: *default_config
                  commands:
                    - "make titan-invoca-tags"
                    - "make test-titan-invoca-tags"
            - path:
                - "applications/react/modern/ivr-campaigns/**"
              config:
                - label: "IVR Campaigns"
                  <<: *default_config
                  commands:
                    - "make titan-ivr-campaigns"
                    - "make test-titan-ivr-campaigns"
            - path:
                - "applications/react/legacy/partner-platforms/**"
              config:
                - label: "Partner Platforms"  
                  <<: *default_config
                  commands:
                    - "make titan-partner-platforms"
                    - "make test-titan-partner-platforms"
            - path:
                - "applications/react/legacy/bulk-number-management/**"
              config:
                - label: "Bulk Number Management"
                  <<: *default_config
                  commands:
                    - "make titan-bulk-number-management"
                    - "make test-titan-bulk-number-management"
            - path:
                - "applications/react/legacy/customer-requests/**"
              config:
                <<: *default_config
                commands:
                  - "make titan-customer-requests"
                  - "make test-titan-customer-requests"
            - path:
                - "applications/react/modern/active-ai/**"
              config:
                <<: *default_config
                commands:
                    - "make titan-active-ai"
                    - "make test-titan-active-ai"
            - path:
                - "applications/react/modern/signals/**"
              config:
                - label: "Signals"
                  <<: *default_config
                  commands:
                      - "make titan-signals"
                      - "make test-titan-signals"
```

Shows:

```
INFO[0000] --- :one: monorepo-diff v2.5.0
--
  | INFO[2022-12-06T22:43:41Z] Running diff command: git diff --name-only $(head -n 1 last_successful_build)
  | FATA[2022-12-06T22:43:41Z] diff command failed: command `git` failed: exit status 128
  | 🚨 Error: The command exited with status 1
```

**Comment by adikari** [comment]
This command `echo $(git rev-parse HEAD) > last_successful_build` is using a variable `last_successful_build`. Are you setting it somewhere or not? If not it will fail for that reason.

**Comment by adikari** [comment]
I will play around with this later and get back.

**Comment by adikari** [comment]
Unfortunately I did not have enough time to look into this. Hopefully will have some time next week

**Comment by dep** [comment]
@adikari ok thank you. It is a bit of a blocker for us so definitely appreciate it once you have time. 

Unless you have an idea for a diff that will only check for changes against `origin/main` for *only* the changed files on my branch.  `git diff --name-only origin/main` for instance will show upstream main changes as well and would cause tests on the branch to run unnecessary.

**Comment by dep** [comment]
Actually that simple example seems to fail as well 🤔

```
# Default pipeline from cli
default_config: &default_config
  agents:
    queue: nodejs-16

steps:
  - label: "Unit Test Pipeline"
    plugins:
      - monebag/monorepo-diff#v2.5.0:
          diff: "git diff --name-only origin/main"
          watch:
            - path:
                - "applications/react/modern/feature-administration/**"
              config:
                - label: "Feature Administration"
                  <<: *default_config
                  commands:
                    - "make titan-feature-administration"
                    - "make test-titan-feature-administration"
```

Error:

```
$ /buildkite/plugins/github-com-monebag-monorepo-diff-buildkite-plugin-v2-5-0/hooks/command
https://github.com/monebag/monorepo-diff-buildkite-plugin/releases/download/v2.5.0/monorepo-diff-buildkite-plugin-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3293k  100 3293k    0     0  10.8M      0 --:--:-- --:--:-- --:--:-- 10.8M
INFO[0000] --- :one: monorepo-diff v2.5.0
INFO[2022-12-12T15:07:49Z] Running diff command: git diff --name-only HEAD~1
Generated Pipeline:
steps:
- {}
 
FATA[2022-12-12T15:07:49Z] +++ failed to upload pipeline: command `buildkite-agent` failed: exit status 1
🚨 Error: The command exited with status 1
```
