### ISSUE TITLE
Generating pipeline with no steps

### ISSUE THREAD

**Issue by orolega** [monebag/monorepo-diff-buildkite-plugin#135]
After updating to version 2.5.9, my pipeline is failing due to the generated pipeline having no steps. The paths that are watched in this step were not modified so I would expect them to be skipped rather than generating an empty pipeline. 

Output is like so:
```
Running diff command: .buildkite/diff.sh
Generated Pipeline:
steps: []
```

So basically by pipeline.yaml looks like the below. It is failing if I modify something in path "B" per the above generated empty pipeline.

```
plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/diff.sh"
          watch:
            - path:
                 - "A"
               config:
                .....
```

**Comment by adikari** [comment]
@orolega I will have a look into this next week when I have some free time. In this scenario, what used to happen before? Did it used to skip generating pipelines and no pipeline was uploaded?

**Comment by orolega** [comment]
Correct. It would skip generating anything for that step and begin the next step in the pipeline. I've outlined it a bit better below. 

If we were to edit only something in the path "B" this pipeline fails now on Step A with that original error, whereas before it would mark the step as complete without having done the command step.

Note I am aware that multiple path steps can be defined under watch. This is just a minimal reproducible example

```
steps:
  - label: "Step A"
    plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/diff.sh"
          watch:
            - path:
                - "A"
              config:
                command: 'echo "Step A"'
  - label: "Step B"
    plugins:
      - monebag/monorepo-diff#v2.5.9:
          diff: ".buildkite/diff.sh"
          watch:
            - path:
                - "B"
              config:
                command: 'echo "Step B"'
```




To get around this we have had to add the below to every step as a work around which is not ideal

```
  - path:
      - "*"
      - "**/*"
      - ".*"
    config:
      command: 'echo "default"'
```
